### ISSUE TITLE
Clear handler_cache when the handler class for a spec is changed.

### ISSUE THREAD

**Issue by danielballan** [bluesky/event-model#114]
While we were debugging a beamline issue together, @mrakitin pointed out that registering a handler for some spec should cause any entries in the `Filler._handler_cache` associated with that spec to be cleared. Otherwise, if the user tried to update the `Filler.handler_registry` and then re-access data, they will confusingly be handed instances of the old class.

One way to implement this would be to make `handler_registry`, which is currently just a `dict`, a special `dict` subclass that can do extra things on `__setitem__`.

**Comment by tacaswell** [comment]
This is handled in the databroker version: https://github.com/bluesky/databroker/blob/8fbc207bd4e03c41318ea272e5a889fcf505ad9c/databroker/assets/base_registry.py#L185-L202

by having methods to add / remove handlers.

If you made `Filler.handler_registry` a special dict it would have to know about it's parent and the reach up to it's parents cache to clear it which seems a bit odd.

**Comment by danielballan** [comment]
@tacaswell I had to dash off this comment in a hurry while people were waiting to go to dinner, but given more time I would have added somethign like, "And now I understand why @tacaswell made special methods for this in the original implementation. :sheep:."

However, the databroker version has a public `handler_reg` dict as well:

```py
In [20]: db.reg._handler_cache                                                                                                                                                                
Out[20]: LRU(max_size=128, on_miss=None, values={('2d65c498-9e9c-4e2c-859b-aef6f11935e7', 'NumpySeqHandler'): <ophyd.sim.NumpySeqHandler object at 0x7fc1f53c9dd8>})

In [21]: db.reg.handler_reg['NPY_SEQ'] = 'foo'                                                                                                                                                

In [22]: db.reg._handler_cache                                                                                                                                                                
Out[22]: LRU(max_size=128, on_miss=None, values={('2d65c498-9e9c-4e2c-859b-aef6f11935e7', 'NumpySeqHandler'): <ophyd.sim.NumpySeqHandler object at 0x7fc1f53c9dd8>})
```

I think special methods for (de)registration are the way to go, and further that the public `handler_registry` attribute should be a property that returns a Frozen dict.
