### ISSUE TITLE
Add convenience methods to DocumentRouter

### ISSUE THREAD

**Issue by jklynch** [bluesky/event-model#165]
I propose some convenience methods for DocumentRouter along these lines:

- DocumentRouter.start_doc()
      return the start document or raise an Exception if the start document has not been seen yet
- DocumentRouter.descriptor_for_event(event_doc)
   return the descriptor document associated with the given event document from a dictionary of uid --> descriptor
- DocumentRouter.stream_name(event_doc)
      given an event document return its stream name by looking up the event's descriptor in a dictionary of uid --> descriptor

I find myself reimplementing this functionality virtually every time I subclass DocumentRouter.

**Comment by tacaswell** [comment]
I'm sold on the first two if we already keep enough state to answer that question, a bit skeptical but still net positive if we have to add the state tracking.

The third seems likes `self.descriptor_for_event(event_doc)['name']` so neutral on it.

**Comment by jklynch** [comment]
addressed by #166
