### ISSUE TITLE
Projection Schema could provide stronger validation

### ISSUE THREAD

**Issue by dylanmcreynolds** [bluesky/event-model#183]
Several parts of the projection schema a mutually exclusive. For example, you can either have type=computed or a type=linked. Currently, the schema allows for linked types with computed attributes. It would be nice if the schema provided stronger validation for this case. There might be additional opportunities for stronger validation.

**Comment by danielballan** [comment]
Related to an old issue, https://github.com/bluesky/event-model/issues/76. Validation could be stricter across the board by leveraging jsonschema to a fuller extent and further by enforcing anything that cannot be expressed in jsonschema in Python code in the document composition function.

**Comment by thomascobb** [comment]
We have been using https://pydantic-docs.helpmanual.io/ for this. You can express your json schema in terms of Python dataclass-style classes, which can be exported to a json schema, and add custom validators in Python for the more difficult cases that will be picked up when you instantiate the objects.

**Comment by danielballan** [comment]
Thanks, @thomascobb. That seems like a good direction to go in here.
