### ISSUE TITLE
Unpin jsonschema in requirements?

### ISSUE THREAD

**Issue by dylanmcreynolds** [bluesky/event-model#193]
The travis configuration effectively pins it to jsonschema 2.x because of an issue with PIP sometimes pulling down 2 instead of 3.

I raised this an issue in slack, and @tacaswell said "we should probably un-pin the jsonschema version".

**Comment by danielballan** [comment]
I thought he was suggesting un-pinning it in our requirements. I think we need to keep pinning it in Travis to ensure that it keeps working on 2 and 3.

**Comment by dylanmcreynolds** [comment]
that's a little confusing, in requirements.txt:

`jsonschema>=3.0.0`

**Comment by danielballan** [comment]
Right. Since pip sometimes does not respect pins (long story) we sometimes get 2.x in spite of that pin. For this reason, we restored compact with both 2 and 3 and continue to test on both. Given that, there is no reason to continue to pin in the requirements file.
