### ISSUE TITLE
Python minimum version/using 3.8+ features

### ISSUE THREAD

**Issue by ksunden** [bluesky/event-model#230]
https://github.com/bluesky/event-model/blob/eac55ca21e54328a7fc1f16fea71e56460ed6a58/event_model/__init__.py#L14

`importlib.metadata` was added in python 3.8, but event-model does not either specify 3.8 as minimum version or include the [backport pypi package](https://pypi.org/project/importlib-metadata/) as a conditional dependency.

Thus it will install on python 3.7 but fail upon use unless the pypi backport is installed otherwise.

**Comment by mrakitin** [comment]
I am 👍 for excluding Python 3.7 from the supported versions. We do it in a few other projects.

**Comment by ksunden** [comment]
also of note, the unit tests GHA is not actually running (and hasn't been for 2 years)

Does not seem to be set up to run on PRs and scheduled pipelines get disabled after 60 days of inactivity (which is itself annoying because one of the best reasons to have scheduled actions is to make sure your dependencies don't break an otherwise stable library....)

**Comment by mrakitin** [comment]
Hmm, I've just enabled https://github.com/bluesky/event-model/actions/workflows/testing.yml.

**Comment by ksunden** [comment]
Hmmm... the workflow itself does indicate it should run on PR, but seems like it hasn't been since it was disabled because of the scheduled runs...


Slightly buried in their docs, and it does not make it clear from this that being disabled will disable it _everywhere_, but that seems to be the case...

https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#disabling-and-enabling-workflows

**Comment by danielballan** [comment]
I propose making one release that fixes 3.7 before we drop it.

**Comment by danielballan** [comment]
Thanks for flagging this @ksunden. I ended up here because the databroker CI is also failing (on Python 3.7) due to this issue. https://github.com/bluesky/databroker/actions/runs/3626380641/jobs/6115321137
