### ISSUE TITLE
Draft release notes and expose `event_descriptor` `Limits`/`LimitsRange`

### ISSUE THREAD

**Issue by evalott100** [bluesky/event-model#317]
We'll do a new minor release, since both the above should be quick to review we'll do them both in the same PR.

**Comment by evalott100** [comment]
On exposing `Limits`, `LimitsRange` from top level event-model. Currently the only document from `documents` we're doing this with is `Dtype`:

```
__all__ = [
    "Dtype",
    "DocumentNames",
    "schemas",
    "schema_validators",
    "compose_run",
    "__version__",
]
```

I would have a minor preference for keeping all our document imports `from event_model.documents import SomeDocument`, but happy to move to `event_model` if it's preferred.

**Comment by coretl** [comment]
@danielballan thoughts?

I don't mind if it's `from event_model import Dtype, Limits` or `from event_model.documents import Dtype, Limits`, but we should pick one or the other and be consistent.

**Comment by evalott100** [comment]
> I don't mind if it's `from event_model import Dtype, Limits` or `from event_model.documents import Dtype, Limits` 
Whenever I've added things thus far I've gone with the latter.
