### ISSUE TITLE
Add rechunk_event_page, rechunk_datum_page.

### ISSUE THREAD

**Issue by danielballan** [bluesky/event-model#49]
[Edited per first comment below]

```py
def rechunk_event_pages(event_pages, chunk_size):
    "Yield chunks with up to chunk_size Events."
    ...
```

**Comment by tacaswell** [comment]
May be more useful to take a generator of event_pages so that we can use this to make _bigger_ event pages as well as smaller one.s

**Comment by awalter-bnl** [comment]
This sounds like a good idea.

**Comment by danielballan** [comment]
We might also want a coroutine version of this. This is, in effect, the `Paginator` component that we had planned to build once https://github.com/NSLS-II/bluesky/pull/1125 finally lands.
